# Generated by Django 3.2.4 on 2021-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_users_finished'),
        ('authentication', '0002_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
